In [79]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import Lasso,Ridge,ElasticNet
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split,GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [4]:
df= pd.read_csv('Advertising.csv',index_col=[0])

In [5]:
df.head()

TV  radio  newspaper  sales
1  230.1   37.8       69.2   24.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [6]:
df.isnull().sum()

TV           0
radio        0
newspaper    0
sales        0
dtype: int64

In [9]:
df.duplicated().sum()

0

In [12]:
target=df[['sales']]

In [13]:
features=df.drop(columns='sales')

In [17]:
std_sca=StandardScaler()
features=pd.DataFrame(std_sca.fit_transform(features),columns=features.columns)

In [18]:
features.head()

TV     radio  newspaper
0  0.969852  0.981522   1.778945
1 -1.197376  1.082808   0.669579
2 -1.516155  1.528463   1.783549
3  0.052050  1.217855   1.286405
4  0.394182 -0.841614   1.281802

In [55]:
x_train,x_test,y_train,y_test=train_test_split(features,target,train_size=0.75,random_state=100)

In [56]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(150, 3)
(50, 3)
(150, 1)
(50, 1)


In [100]:
## Lasso
lasso=Lasso(alpha=2)

In [101]:
lasso.fit(x_train,y_train)

Lasso(alpha=2)

In [102]:
lasso.coef_

array([2.22001031, 0.91804183, 0.        ])

In [72]:
lasso.intercept_

array([13.90816041])

In [73]:
y_pred= lasso.predict(x_test)

In [74]:
r2_score(y_test,y_pred)

0.8493349423470539

In [75]:
y_pred1= lasso.predict(x_train)

In [76]:
r2_score(y_train,y_pred1)

0.8312073733000599

### Gridsearch

In [80]:
params= dict(alpha=range(1,50))

In [81]:
grid_search=GridSearchCV(lasso,params)

In [82]:
grid_search.fit(x_train,y_train)

GridSearchCV(estimator=Lasso(alpha=1), param_grid={'alpha': range(1, 50)})

In [83]:
grid_search.best_params_

{'alpha': 1}

## Ridge

In [108]:
ridge=Ridge(alpha=1)

In [109]:
ridge.fit(x_train,y_train)

Ridge(alpha=1)

In [110]:
ridge.coef_

array([[3.89978827, 2.76730293, 0.13206523]])

In [111]:
ridge.intercept_

array([13.9043926])

In [112]:
y_pred= ridge.predict(x_test)

In [113]:
r2_score(y_test,y_pred)

0.9012560817135826

In [114]:
## Grid_Search
grid_search=GridSearchCV(ridge,params)

In [115]:
grid_search.fit(x_train,y_train)

GridSearchCV(estimator=Ridge(alpha=1), param_grid={'alpha': range(1, 50)})

In [107]:
grid_search.best_params_

{'alpha': 1}

### ElasticNet

In [168]:
elasticnet=ElasticNet(alpha=1,l1_ratio=0.9)

In [169]:
elasticnet.fit(x_train,y_train)

ElasticNet(alpha=1, l1_ratio=0.9)

In [170]:
elasticnet.coef_

array([2.9109241 , 1.80205461, 0.        ])

In [171]:
elasticnet.intercept_

array([13.90642771])

In [172]:
y_pred= elasticnet.predict(x_test)

In [173]:
r2_score(y_test,y_pred)

0.8316485979141865

In [164]:
params=dict(alpha=range(1,100),l1_ratio=np.arange(0,1,0.1))

In [165]:
grid_search=GridSearchCV(elasticnet,params)

In [166]:
grid_search.fit(x_train,y_train)

GridSearchCV(estimator=ElasticNet(alpha=1, l1_ratio=0.8),
             param_grid={'alpha': range(1, 100),
                         'l1_ratio': array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])})

In [167]:
grid_search.best_params_

{'alpha': 1, 'l1_ratio': 0.9}